import { GameState } from '@shared/types';

// Mock-Spielzustand für visuelle Entwicklung (Step 3)
export const MOCK_MY_ID = 'p1';

export const mockState: GameState = {
  roomId: 'TEST',
  turn: 3,
  currentPlayerId: 'p1',
  turnPhase: 'play',
  winner: null,
  pendingReaction: null,
  dynamiteOwnerId: null,
  deck: Array.from({ length: 34 }, (_, i) => ({
    id: `deck_${i}`,
    type: 'bang' as const,
    category: 'action' as const,
    suit: 'spades' as const,
    value: 'A' as const,
  })),
  discardPile: [
    { id: 'd1', type: 'bang', category: 'action', suit: 'hearts', value: 'Q' },
    { id: 'd2', type: 'missed', category: 'action', suit: 'clubs', value: '7' },
  ],
  players: [
    {
      id: 'p1',
      name: 'Doc Holliday',
      role: 'sheriff',
      character: 'slabTheKiller',
      maxHp: 5,
      hp: 4,
      isAlive: true,
      isSheriff: true,
      isReady: true,
      bangPlayedThisTurn: 0,
      weapon: { id: 'w1', type: 'volcanic', category: 'weapon', suit: 'spades', value: '2' },
      table: [],
      hand: [
        { id: 'h1', type: 'bang', category: 'action', suit: 'hearts', value: 'K' },
        { id: 'h2', type: 'bang', category: 'action', suit: 'diamonds', value: 'J' },
        { id: 'h3', type: 'missed', category: 'action', suit: 'clubs', value: '8' },
        { id: 'h4', type: 'beer', category: 'action', suit: 'hearts', value: '6' },
        { id: 'h5', type: 'catBalou', category: 'action', suit: 'diamonds', value: '9' },
        { id: 'h6', type: 'panic', category: 'action', suit: 'hearts', value: 'J' },
      ],
    },
    {
      id: 'p2',
      name: 'Jesse James',
      role: 'outlaw',
      character: 'jesseJones',
      maxHp: 4,
      hp: 4,
      isAlive: true,
      isSheriff: false,
      isReady: true,
      bangPlayedThisTurn: 0,
      weapon: null,
      table: [
        { id: 't1', type: 'barrel', category: 'equipment', suit: 'spades', value: '3' },
      ],
      hand: Array.from({ length: 4 }, (_, i) => ({
        id: `?h2_${i}`,
        type: 'bang' as const,
        category: 'action' as const,
        suit: 'spades' as const,
        value: 'A' as const,
      })),
    },
    {
      id: 'p3',
      name: 'Billy the Kid',
      role: 'deputy',
      character: 'willyTheKid',
      maxHp: 4,
      hp: 2,
      isAlive: true,
      isSheriff: false,
      isReady: true,
      bangPlayedThisTurn: 0,
      weapon: { id: 'w2', type: 'winchester', category: 'weapon', suit: 'clubs', value: '5' },
      table: [],
      hand: Array.from({ length: 2 }, (_, i) => ({
        id: `?h3_${i}`,
        type: 'bang' as const,
        category: 'action' as const,
        suit: 'spades' as const,
        value: 'A' as const,
      })),
    },
    {
      id: 'p4',
      name: 'Belle Starr',
      role: 'outlaw',
      character: 'calamityJanet',
      maxHp: 4,
      hp: 3,
      isAlive: true,
      isSheriff: false,
      isReady: true,
      bangPlayedThisTurn: 0,
      weapon: null,
      table: [
        { id: 't2', type: 'mustang', category: 'equipment', suit: 'hearts', value: '8' },
        { id: 't3', type: 'jail', category: 'equipment', suit: 'spades', value: 'A' },
      ],
      hand: Array.from({ length: 3 }, (_, i) => ({
        id: `?h4_${i}`,
        type: 'bang' as const,
        category: 'action' as const,
        suit: 'spades' as const,
        value: 'A' as const,
      })),
    },
  ],
};
